version: '3'
services:
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=2^J9rqrKWgKBfRvC
      - MYSQL_DATABASE=opulence
      - MYSQL_PASSWORD=2^J9rqrKWgKBfRvC
      - MYSQL_USER=opulence
    ports:
      - "3305:3306"

  php:
    image: abtercms/php:latest
    environment:
      - DB_DRIVER=Opulence\Databases\Adapters\Pdo\MySql\Driver
      - DB_HOST=db
      - DB_USER=opulence
      - DB_PASSWORD=2^J9rqrKWgKBfRvC
      - DB_NAME=opulence
      - DB_PORT=3306
    links:
      - db
    volumes:
      - .:/website
    working_dir: /website
    command: php -S 0.0.0.0:8050 localhost_router.php
    ports:
      - "8050:8050"
